name: Publish release Docker image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish release image
    uses: ./.github/workflows/docker-build.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
