#!/bin/sh
if [ $state.bootstate.update_boot_count -gt 0 ]; then
	S=$state.bootstate.update_system
	let state.bootstate.update_boot_count=$state.bootstate.update_boot_count-1
	echo "Selecting updated system$S (${state.bootstate.update_boot_count} remaining)"
	state -s
else
	S=$state.bootstate.active_system
	echo "Selecting active system$S"
fi
if [ $S = 0 ]; then
	boot system0
else
	if [ $S = 1 ]; then
		boot system1
	fi
fi
